version: '3.7'
services:
  py-api:
    image: rbarbioni/py-api
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    environment:
      ENV_FOR_DYNACONF: docker
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
  db:
    container_name: mysql
    image: mysql:8
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
      MYSQL_ROOT_PASSWORD: api
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.30'
          memory: 250M
      restart_policy:
        condition: on-failure