[default]
APPLICATION_NAME="py-api"
APPLICATION_VERSION="1.0.0"
DEBUG=false
LOG_LEVEL="DEBUG"
GUNICORN_THREADS=1
GUNICORN_WORKERS=1
DATABASE_URL="mysql+pymysql://api:api@localhost/api"
DATABASE_MIGRATION=true
SWAGGER_URL="/api/docs"
SWAGGER_FILE="swagger.json"

[docker]
DATABASE_URL="mysql+pymysql://api:api@db/api"

[production]
DATABASE_URL="CONSIDER USING ENVIRONMENT VARIABLES FOR PRODUCTION"
GUNICORN_THREADS=10
GUNICORN_WORKERS=2